#! /bin/bash -l 
# 
#SBATCH -A naiss2023-22-247
#SBATCH -p core -n 6
#SBATCH -t 10:00 
#SBATCH --qos=short -J test_run


# Activate Anaconda work environment for OpenDrift
source /home/${USER}/.bashrc
conda activate fl_flower

./run_server.sh &
./run_clients.sh &
wait 
