#!/bin/bash -l
#SBATCH -A naiss2023-22-247
#SBATCH -M snowy
#SBATCH -p node
#SBATCH -N 20
#SBATCH -t 2:00:00 
#SBATCH --gpus=20
#SBATCH --gpus-per-node=1
#SBATCH --ntasks-per-node=1
#SBATCH -J gpu_run_test
#SBATCH -D ./

# Activate anaconda environment for flower framework
source /home/${USER}/.bashrc
conda activate fl_flower

#hostnames=$(srun hostname)
hostnames=$SLURM_NODELIST
echo "Fetched Hostnames are $hostnames"
wait

FILES="exp_configs/*"
for f in $FILES
do  
    echo "Running experiment with $f config file."
    srun run_experiment.sh $hostnames $f
    wait
done

cp -r $SNIC_TMP/ ~/deeplearning/decentralized-FD/temp/results/
