#!/bin/bash
salloc -A naiss2023-22-247 -p node -N 6 -M snowy --gpus 6 --gpus-per-node=1 -t 1:00:00
ssh s178 "conda activate fl_flower; cd deeplearning/decentralized-FD; python src/run_fl_clients.py --server_address="172.18.5.177:59990" --total_clients=5 --num_clients=1 --start_cid=0 --config_file="src/configs/exp_configs.yaml"" &